### ISSUE TITLE
Recommended to improve help information

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/gitea-actions-runner#4]
It is recommended to add and improve help information

```
Run GitHub actions locally by specifying the event name (e.g. `push`) or an action name directly.

Usage:
  act [command]

Available Commands:
  daemon      Run as a runner daemon
  help        Help about any command
  register    Register a runner to the server
  svc         

Flags:
      --env-file string   Read in a file of environment variables. (default ".env")
  -h, --help              help for act
  -v, --version           version for act

Use "act [command] --help" for more information about a command.
```

```
Usage:
  act svc [command]

Available Commands:
  install     
  run         
  start       
  stop        
  uninstall   

Flags:
  -h, --help   help for svc

Global Flags:
      --env-file string   Read in a file of environment variables. (default ".env")

Use "act svc [command] --help" for more information about a command.
```

_Originally posted by @oilrich25 in https://github.com/ChristopherHX/gitea-actions-runner/issues/1#issuecomment-1839903514_

**Comment by oilrich25** [comment]
can  `ChristopherHX/gitea-actions-runner` supports `nektos/act`?

**Comment by oilrich25** [comment]
I saw that https://github.com/ChristopherHX/gitea-actions-runner/blob/main/go.mod#L56C30-L58 of `ChristopherHX/gitea-actions-runner` also uses `nektos/act`. If using docker, how to configure `ChristopherHX/gitea-actions-runner`?

Also, can the docker configurations of `actions-runner/bin/Runner.Worker` and `nektos/act` be set simultaneously in `ChristopherHX/gitea-actions-runner`?

**Comment by oilrich25** [comment]
> > `ChristopherHX/gitea-actions-runner` seems to currently only support the official GitHub runner binary. Can `ChristopherHX/gitea-actions-runner` support the `nektos/act` binary?
> 
> No using nektos/act binary directly as a worker is not possible.
> 
> if you want to use `nektos/act` for Gitea you have two options
> 
> * Use act_runner directly via their full Gitea Act fork
> * Download this worker https://github.com/ChristopherHX/github-act-runner based on act
>   
>   * All worker of gitea-actions-runner have to speak the actions/runner protocol, act doesn't support that directly)
>   * change runner_worker
>     ```json
>     {
>       "runner_worker": [ "github-act-runner", "worker" ]
>     }
>     ```
>   * Note: no pwsh/python wrapper required both of my runner apps speak a common worker protocol
>   * You can also insert the full path to the github-act-runner or even ssh into another machine of the same network
> 
> You can technically put a script between the runner_worker and forward stdin/stdout and the network, so you can spawn a tart vm and run the command inside of it.

OK

**Comment by oilrich25** [comment]
> > `ChristopherHX/gitea-actions-runner` seems to currently only support the official GitHub runner binary. Can `ChristopherHX/gitea-actions-runner` support the `nektos/act` binary?
> 
> No using nektos/act binary directly as a worker is not possible.
> 
> if you want to use `nektos/act` for Gitea you have two options
> 
> * Use act_runner directly via their full Gitea Act fork
> * Download this worker https://github.com/ChristopherHX/github-act-runner based on act
>   
>   * All worker of gitea-actions-runner have to speak the actions/runner protocol, act doesn't support that directly)
>   * change runner_worker
>     ```json
>     {
>       "runner_worker": [ "github-act-runner", "worker" ]
>     }
>     ```
>   * Note: no pwsh/python wrapper required both of my runner apps speak a common worker protocol
>   * You can also insert the full path to the github-act-runner or even ssh into another machine of the same network
> 
> You can technically put a script between the runner_worker and forward stdin/stdout and the network, so you can spawn a tart vm and run the command inside of it.

Does `https://github.com/ChristopherHX/github-act-runner` support the registration method of gitea? Can I register through gitea's token?

**Comment by oilrich25** [comment]
I saw that task.go in `ChristopherHX/gitea-actions-runner` contains docker parsing, but in fact `ChristopherHX/gitea-actions-runner` does not support docker, right?
https://github.com/ChristopherHX/gitea-actions-runner/blob/8ac05c900d114cf70463b648ddca7b214f8cb18a/runtime/task.go#L521-L526

**Comment by oilrich25** [comment]
> > but in fact `ChristopherHX/gitea-actions-runner` does not support docker, right?
> 
> Docker should be fully functional on Linux.
> 
> If you want to use windows container on windows you would need to use my actions/runner fork as runner worker https://github.com/ChristopherHX/runner.server.
> 
> > This runner does support service container
> > This runner does support https://github.com/actions/runner-container-hooks
> 
> Maybe you got confused by the does/doesn't sequence.

If using docker, how to configure it? I try ./gitea-actions-runner-0.0.3-linux-amd64 register
```
INFO Enter the runner labels, leave blank to use the default labels (comma-separated, for example, self-hosted,ubuntu-latest):
ubuntu-latest,ubuntu-20.04:docker://node:16-bullseye
```
The generated .runner file is
```
{
   "id": 298,
   "uuid": "2475bai8-9csa-44e5-880a-01fa4a538db3",
   "name": "ouchiharbor.com",
   "token": "507dfce2b8a284c859deb6b445b361d46aft6c44",
   "address": "http://192.168.1.10:3000/",
   "labels": [
     "ubuntu-latest",
     "ubuntu-20.04:docker://node:16-bullseye"
   ],
   "runner_worker": [
     "pwsh",
     "actions-runner-worker.ps1",
     "actions-runner/bin/Runner.Worker"
   ]
}
```
However, during actual use, it was found that when runs-on: ubuntu-20.04 was actually executed, ubuntu-latest was actually executed, that is, ubuntu-20.04:docker://node:16-bullseye did not take effect.

**Comment by oilrich25** [comment]
> Ah that syntax doesn't work.
> 
> You should write
> 
> ```
> ...
> runs-on: ubuntu-20.04
> container: node:16-bullseye
> ....
> ```
> 
> In your workflow.
> 
> I didn't adapt all weird stuff from the Gitea People.
> 
> My concept is more like GitHub Actions.

OK

**Comment by oilrich25** [comment]
```
```
  ubuntu-latest:
    runs-on: ubuntu-latest
    container: christopherhx/runner-images:ubuntu20-runner-medium-hostedtoolcache-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.job }}
      - run: uname -a
```

```
Current runner version: '2.311.0'
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:N/A)
Complete job name: android
##[group]Checking docker version
##[command]/snap/bin/docker version --format '{{.Server.APIVersion}}'
'1.41'
Docker daemon API version: '1.41'
##[command]/snap/bin/docker version --format '{{.Client.APIVersion}}'
'1.41'
Docker client API version: '1.41'
##[endgroup]
##[group]Clean up resources from previous jobs
##[command]/snap/bin/docker ps --all --quiet --no-trunc --filter "label=ad672f"
##[command]/snap/bin/docker network prune --force --filter "label=ad672f"
##[endgroup]
##[group]Create local container network
##[command]/snap/bin/docker network create --label ad672f github_network_0821b6895eb8492387cc076a24b66045
f1f9a4d61a6427d1e9f547f4bbba9ce36b91af5c7868484d21a20965ad1e37c4
##[endgroup]
##[group]Starting job container
##[command]/snap/bin/docker pull christopherhx/runner-images:ubuntu20-runner-medium-hostedtoolcache-latest
Error response from daemon: pull access denied for christopherhx/runner-images, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
##[warning]Docker pull failed with exit code 1, back off 7.398 seconds before retry.
##[command]/snap/bin/docker pull christopherhx/runner-images:ubuntu20-runner-medium-hostedtoolcache-latest
Error response from daemon: pull access denied for christopherhx/runner-images, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
##[warning]Docker pull failed with exit code 1, back off 4.897 seconds before retry.
##[command]/snap/bin/docker pull christopherhx/runner-images:ubuntu20-runner-medium-hostedtoolcache-latest
Error response from daemon: pull access denied for christopherhx/runner-images, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
##[error]Docker pull failed with exit code 1
Remove container network: github_network_0821b6895eb8492387cc076a24b66045
##[command]/snap/bin/docker network rm github_network_0821b6895eb8492387cc076a24b66045
github_network_0821b6895eb8492387cc076a24b66045
Cleaning up orphan processes
Finished
```

```
# docker images
REPOSITORY                                   TAG                                             IMAGE ID       CREATED         SIZE
christopherhx/runner-images                  ubuntu20-runner-medium-hostedtoolcache-latest   79a122a89493   N/A             25.1GB
ghcr.io/christopherhx/runner-images          ubuntu20-runner-medium-hostedtoolcache-latest   79a122a89493   N/A             25.1GB
```
```

**Comment by oilrich25** [comment]
#https://github.com/ChristopherHX/runner-image-blobs/issues/1

**Comment by oilrich25** [comment]
> > but in fact `ChristopherHX/gitea-actions-runner` does not support docker, right?
> 
> Docker should be fully functional on Linux.
> 
> If you want to use windows container on windows you would need to use my actions/runner fork as runner worker https://github.com/ChristopherHX/runner.server (Note: No longer packaged with a bin folder, extract the files into a bin folder. The external folder should be pulled on demand).
> 
> > This runner does support service container
> > This runner does support https://github.com/actions/runner-container-hooks
> 
> Maybe you got confused by the does/doesn't sequence.

### test environment:

I tried downloading `ChristopherHX/runner.server`
```
# https://github.com/ChristopherHX/runner.server/releases/download/v3.11.11/runner.server-win-x64.zip
```
And unzip it and place it in the same directory as the `act_runner` binary program,
```
.
├── actions-runner
│ ├── bin
│ ├── config.sh
│ ├── _diag
│ ├── .env
│ ├── env.sh
│ ├── externals
│ ├── run-helper.cmd.template
│ ├── run-helper.sh.template
│ ├── .runner
│ ├── run.sh
│ ├── safe_sleep.sh
│ └── _work
├── actions-runner-worker.ps1
├── actions-runner-worker.py
├── act_runner
├── runner.server-win-x64
│ ├── checkScripts
│ ├── cs
│ ├── .runner
│ ├── Runner.Worker
│ └── ...
├── cache
│ ├── bolt.db
│ └── cache
├── gitea-actions-runner-log-error.txt
├── gitea-actions-runner-log.txt
└── .runner

```
`.runner`
```
{
   "id": 294,
   "uuid": "59f66b39-5dad-41ce-5aa8-38ccb23d823c",
   "name": "WIN-HMAELFGC2EB",
   "token": "7991639141d50c22a95466613081696c266460d3",
   "address": "http://192.168.1.10:3000/",
   "labels": [
     "windows-2019"
   ],
   "runner_worker": [
     "pwsh",
     "actions-runner-worker.ps1",
     "runner.server-win-x64/Runner.Worker"
   ]
}
```

`runner.server-win-x64\.runner`
```
{"workFolder": "_work"}
```

### Test Results:

```
Wait for exit
System.ArgumentNullException: Value cannot be null. (Parameter 'WorkFolder')
    at GitHub.Runner.Sdk.ArgUtil.NotNullOrEmpty(String value, String name) in /home/runner/work/runner.server/runner.server/src/Runner.Sdk/Util/ArgUtil.cs:line 58
    at GitHub.Runner.Common.HostContext.GetDirectory(WellKnownDirectory directory) in /home/runner/work/runner.server/runner.server/src/Runner.Common/HostContext.cs:line 309
    at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken) in /home/runner/work/runner.server/runner.server/src/Runner.Worker/JobRunner.cs:line 71
    at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken) in /home/runner/work/runner.server/runner.server/src/Runner.Worker/JobRunner.cs:line 201
    at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut) in /home/runner/work/runner.server/runner.server/src/Runner.Worker/Worker.cs:line 108
    at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args) in /home/runner/work/runner.server/runner.server/src/Runner.Worker/Program.cs:line 52
Has exited with code 1 and conclusion 1
##[Error]failed to execute worker exitcode: 1
```

**Comment by oilrich25** [comment]
> > > but in fact `ChristopherHX/gitea-actions-runner` does not support docker, right?
> > 
> > 
> > Docker should be fully functional on Linux.
> > If you want to use windows container on windows you would need to use my actions/runner fork as runner worker https://github.com/ChristopherHX/runner.server (Note: No longer packaged with a bin folder, extract the files into a bin folder. The external folder should be pulled on demand).
> > > This runner does support service container
> > > This runner does support https://github.com/actions/runner-container-hooks
> > 
> > 
> > Maybe you got confused by the does/doesn't sequence.
> 
> ### test environment:
> I tried downloading `ChristopherHX/runner.server`
> 
> ```
> # https://github.com/ChristopherHX/runner.server/releases/download/v3.11.11/runner.server-win-x64.zip
> ```
> 
> And unzip it and place it in the same directory as the `act_runner` binary program,
> 
> ```
> .
> ├── actions-runner-worker.ps1
> ├── actions-runner-worker.py
> ├── act_runner
> ├── runner.server-win-x64
> │ ├── checkScripts
> │ ├── cs
> │ ├── .runner
> │ ├── Runner.Worker
> │ └── ...          // Omit some content display
> ├── cache
> │ ├── bolt.db
> │ └── cache
> ├── gitea-actions-runner-log-error.txt
> ├── gitea-actions-runner-log.txt
> └── .runner
> ```
> 
> `.runner`
> 
> ```
> {
>    "id": 294,
>    "uuid": "59f66b39-5dad-41ce-5aa8-38ccb23d823c",
>    "name": "WIN-HMAELFGC2EB",
>    "token": "7991639141d50c22a95466613081696c266460d3",
>    "address": "http://192.168.1.10:3000/",
>    "labels": [
>      "windows-2019"
>    ],
>    "runner_worker": [
>      "pwsh",
>      "actions-runner-worker.ps1",
>      "runner.server-win-x64/Runner.Worker"
>    ]
> }
> ```
> 
> `runner.server-win-x64\.runner`
> 
> ```
> {"workFolder": "_work"}
> ```
> 
> ### Test Results:
> ```
> Wait for exit
> System.ArgumentNullException: Value cannot be null. (Parameter 'WorkFolder')
>     at GitHub.Runner.Sdk.ArgUtil.NotNullOrEmpty(String value, String name) in /home/runner/work/runner.server/runner.server/src/Runner.Sdk/Util/ArgUtil.cs:line 58
>     at GitHub.Runner.Common.HostContext.GetDirectory(WellKnownDirectory directory) in /home/runner/work/runner.server/runner.server/src/Runner.Common/HostContext.cs:line 309
>     at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken) in /home/runner/work/runner.server/runner.server/src/Runner.Worker/JobRunner.cs:line 71
>     at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken) in /home/runner/work/runner.server/runner.server/src/Runner.Worker/JobRunner.cs:line 201
>     at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut) in /home/runner/work/runner.server/runner.server/src/Runner.Worker/Worker.cs:line 108
>     at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args) in /home/runner/work/runner.server/runner.server/src/Runner.Worker/Program.cs:line 52
> Has exited with code 1 and conclusion 1
> ##[Error]failed to execute worker exitcode: 1
> ```


**My final solution was to unzip `runner.server-win-x64.zip` and replace the original `actions-runner\bin` directory.**
