### ISSUE TITLE
How to resolve the issue 'Parameter 'using: go' is not supported'?

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/gitea-actions-runner#8]
```
**Problem Description:**
I encountered an error while using GitHub Actions, and the error message is as follows:

```plaintext
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: go' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Fail to load actions/go-hashfiles/v0.0.1/action.yml
```

### Relevant Information:

- Current runner version: '2.311.0'
- Secret source: Actions
- Prepare workflow directory
- Prepare all required actions
- Download action repository information:
    - 'actions/checkout@v3'
    - 'actions/setup-go@v3'
    - 'actions/go-hashfiles@v0.0.1'
    - 'actions/cache@v3'
    - 'crazy-max/ghaction-import-gpg@v5'
    - 'goreleaser/goreleaser-action@v4'
    - 

### Cause of the Problem:
During execution, an error occurred due to the unsupported parameter using: go. The error message suggests using 'docker', 'node12', 'node16', or 'node20' instead.

**Comment by oilrich25** [comment]
> This is an unofficial extension to the action.yml format of GitHub Actions, only Gitea Act (act_runner) support that.
> 
> Neither actions/runner, github-act-runner or nektos/act support it.
> 
> `go-hashfiles` is not supported outside of Gitea Act's fork. actions/runner has `${{ hashfiles('path/to/files/to/hash') }}` for the hashing files.
> 
> _Are you shure you don't want to run act_runner via labels like `ubuntu-latest:host`, `windows-latest:host`, `macos-latest:host` or `self-hosted:host`?_
> 
> I added the HostEnvironment capability (aka no container mode) to all derviates of nektos/act, including Gitea Actions.

Yes, I forgot to remove go-hashfiles. It works fine now.
